<a href="https://colab.research.google.com/github/SahooShuvranshu/AI-ML-Internship-CTTC-2026/blob/main/ANN_Models_Iris_DataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iris Data Set | Categorical

26th June 2026

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
iris = pd.read_csv(r"/content/iris.data", header=None)
iris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
iris.columns = ['SL', 'SW', 'PL', 'PW', 'FlowerType']
iris

      SL   SW   PL   PW      FlowerType
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
iris.isnull().sum()

SL            0
SW            0
PL            0
PW            0
FlowerType    0
dtype: int64

In [5]:
iris.dtypes

SL            float64
SW            float64
PL            float64
PW            float64
FlowerType     object
dtype: object

# Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [7]:
iris.FlowerType = lb.fit_transform(iris.FlowerType)
iris.FlowerType.unique()

array([0, 1, 2])

In [8]:
lb.inverse_transform([0,1,2])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# IP/OP Creation

In [9]:
ip = iris.drop('FlowerType', axis=1)
op = iris.FlowerType

# To Categorical

In [10]:
from keras.utils import to_categorical
op = to_categorical(op, 3)

In [11]:
op

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

# Train Test Split

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(ip, op, test_size = 0.2)

# Standard Scaler

In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Training

In [14]:
model = Sequential()
model.add(Dense(20, input_dim=4, activation='relu'))

model.add(Dense(35, activation='relu'))
model.add(Dense(15, activation='relu'))

model.add(Dense(3, activation='softmax'))
model.compile(Adam(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 20)             │           100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 35)             │           735 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │           540 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            48 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,423 (5.56 KB)

 Trainable params: 1,423 (5.56 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=15)

Epoch 1/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 365ms/step - accuracy: 0.3083 - loss: 1.1709 - val_accuracy: 0.2667 - val_loss: 0.9908
Epoch 2/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.4583 - loss: 0.9160 - val_accuracy: 0.5000 - val_loss: 0.8853
Epoch 3/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6583 - loss: 0.8045 - val_accuracy: 0.9667 - val_loss: 0.7661
Epoch 4/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8750 - loss: 0.7347 - val_accuracy: 0.6333 - val_loss: 0.7130
Epoch 5/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.8500 - loss: 0.6237 - val_accuracy: 1.0000 - val_loss: 0.5657
Epoch 6/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.9333 - loss: 0.5128 - val_accuracy: 0.9333 - val_loss: 0.4455
Epoch 7/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9417 - loss: 0.3991 - val_accuracy: 0.9667 - val_loss: 0.3324
Epoch 8/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9583 - loss: 0.3095 - val_accuracy: 0.9333 - val_loss: 0.2613
Epoch 9/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9250 - loss: 0.2283 - val_accuracy: 0.8333 - val_loss: 0.2740
Epoch 10/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9000 - loss: 0.2430 - val_accuracy: 0.8333 - val_loss: 0.2855
Epoch 11/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8833 - loss: 0.2684 - val_accuracy: 0.9667 - val_loss: 0.1132
Epoch 12/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.9083 - loss: 0.1980 - val_accuracy: 0.9667 - val_loss: 0.0945
Epoch 13/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.9333 - loss: 0.1544 - val_accuracy: 1.0000 - val_loss: 0.0720
Epoch 14/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.9750 - loss: 0.1305 - val_accuracy: 1.0000 - val_loss: 0.0655
Epoch 15/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 186ms/step - accuracy: 0.9750 - loss: 0.1047 - val_accuracy: 1.0000 - val_loss: 0.0597

In [17]:
pred = model.predict(x_test)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

array([[9.9385953e-01, 6.1146258e-03, 2.5824902e-05],
       [3.2935934e-03, 9.7504741e-01, 2.1658907e-02],
       [9.4231998e-04, 9.4238025e-01, 5.6677442e-02],
       [9.8870414e-01, 1.1216945e-02, 7.8847785e-05],
       [9.9461901e-01, 5.3543393e-03, 2.6674190e-05],
       [9.9489462e-01, 5.0803293e-03, 2.5080806e-05],
       [9.9048036e-01, 9.4263302e-03, 9.3269467e-05],
       [5.3021882e-04, 9.4697577e-01, 5.2493941e-02],
       [8.1436428e-06, 1.7354542e-01, 8.2644641e-01],
       [9.9185514e-01, 8.0824532e-03, 6.2395717e-05],
       [5.8628124e-04, 8.9941913e-01, 9.9994630e-02],
       [1.2328741e-03, 9.8237127e-01, 1.6395817e-02],
       [9.8582518e-01, 1.4093679e-02, 8.1176098e-05],
       [9.0361141e-07, 5.3220935e-02, 9.4677818e-01],
       [1.7146375e-03, 9.8498994e-01, 1.3295316e-02],
       [2.6469421e-05, 4.9642563e-01, 5.0354797e-01],
       [1.5796601e-06, 3.9006077e-02, 9.6099228e-01],
       [9.7789043e-01, 2.1833688e-02, 2.7596203e-04],
       [4.4922334e-07, 4.8019882e-02, 9.5197964e-01],
       [9.8992902e-01, 9.9882456e-03, 8.2734063e-05],
       [9.9252343e-01, 7.4237385e-03, 5.2748117e-05],
       [6.3330276e-08, 1.2802381e-02, 9.8719770e-01],
       [1.5796601e-06, 3.9006077e-02, 9.6099228e-01],
       [9.9453557e-01, 5.4326756e-03, 3.1829913e-05],
       [5.2629141e-03, 9.7549623e-01, 1.9240817e-02],
       [1.3931723e-04, 7.9700911e-01, 2.0285159e-01],
       [2.0023780e-03, 9.7018403e-01, 2.7813593e-02],
       [1.3993174e-07, 3.6538370e-02, 9.6346152e-01],
       [9.8743802e-01, 1.2495124e-02, 6.6822438e-05],
       [9.9767417e-01, 2.3203588e-03, 5.4839220e-06]], dtype=float32)

In [18]:
p = np.argmax(pred, axis=1)
p

array([0, 1, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2,
       2, 0, 1, 1, 1, 2, 0, 0])

In [19]:
y_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [20]:
y = np.argmax(y_test, axis=1)
y

array([0, 1, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2,
       2, 0, 1, 1, 1, 2, 0, 0])

# Accuracy, Recall, Precision, Average Calculations

In [21]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

ac = accuracy_score(y, p)
rc = recall_score(y, p, average='micro')
pc = precision_score(y, p, average='micro')
f1 = f1_score(y, p, average='micro')

print('Accuracy Score: ', ac)
print('Recall Score: ', rc)
print('Precision Score: ', pc)
print('F1 Score: ', f1)

Accuracy Score:  1.0
Recall Score:  1.0
Precision Score:  1.0
F1 Score:  1.0